kind: Service
apiVersion: v1
metadata:
  name:  jasperserv
spec:
  type: LoadBalancer
  selector:
    app: jasperreports
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
      name: jaspersecure
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: jasperclear
